# Generated by Django 4.0.6 on 2023-04-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_book_content_type_book_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='content_type',
        ),
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.ImageField(null=True, upload_to='book'),
        ),
    ]
