# Generated by Django 4.0.6 on 2023-04-12 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_book_content_type_alter_book_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='content_type',
            field=models.CharField(help_text='The MIMEType of the file', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.BinaryField(editable=True, null=True),
        ),
    ]
