# Generated by Django 4.0.6 on 2023-04-12 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0004_book_content_type_alter_book_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='favorites',
            field=models.ManyToManyField(related_name='favorite_book', through='home.Fav', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fav',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.book'),
        ),
        migrations.AddField(
            model_name='fav',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.publisher'),
        ),
        migrations.AlterUniqueTogether(
            name='fav',
            unique_together={('book', 'user')},
        ),
    ]
