# Generated by Django 4.0.6 on 2023-04-12 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_fav_publisher_book_favorites_fav_book_fav_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
