# Generated by Django 4.0.6 on 2023-04-12 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0006_remove_book_publisher_delete_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='favorites',
            field=models.ManyToManyField(related_name='favorite_books', through='home.Fav', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fav',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favs_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
