# Generated by Django 4.0.6 on 2023-04-13 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0007_alter_book_favorites_alter_fav_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BasketRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.basket')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbasket_books', to='home.book')),
            ],
            options={
                'unique_together': {('basket', 'book')},
            },
        ),
        migrations.AddField(
            model_name='basket',
            name='records',
            field=models.ManyToManyField(related_name='baskets', through='home.BasketRecord', to='home.book'),
        ),
        migrations.AddField(
            model_name='basket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket', to=settings.AUTH_USER_MODEL),
        ),
    ]
