# Generated by Django 4.0.6 on 2023-04-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_order_basketrecord_amount_alter_basketrecord_basket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='destination',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='post_code',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
