# Generated by Django 4.0.6 on 2023-04-14 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_basketrecord_amount_alter_orderrecord_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketrecord',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderrecord',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
