# Generated by Django 4.0.6 on 2023-04-14 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_publisher_name_addressrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addressrecord',
            old_name='owner',
            new_name='user',
        ),
    ]
