# Generated by Django 4.0.6 on 2023-04-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_author_tags_book_tags_publisher_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
