# Generated by Django 4.0.6 on 2023-04-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_basket_total_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketrecord',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='orderrecord',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
