# Generated by Django 4.0.6 on 2023-04-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_basketrecord_total_orderrecord_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='shipping',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=7, null=True),
        ),
    ]
